name: Triple G Indicators Scan

on:
  schedule:
    - cron: "15 4-22 * * 1-5" # Du lundi au vendredi, de 4h15 à 22h15 UTC
    # TEST JOUR : Toutes les heures à la minute 10
    #- cron: "10 * * * *"
  workflow_dispatch: # Permet le lancement manuel

permissions:
  contents: write # Important pour pouvoir pusher les changements de runner_history.json

jobs:
  run-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Download market cache
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: market-cache
      #     path: .
      #   continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # Cache les dépendances pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Triple G Indicators Scan
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REVERSAL_TZ: Europe/Paris
        run: |
          python annual_V2.py
          python sar_break_V6.py
          python index_long_trend_V2.py
          python sms_tim_V2.py

      # - name: Upload market cache
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: market-cache
      #     path: market_cache.pkl
      # python rubbeon_V3.py
      # python annual_V1.py
      #python rubbeon_MTF_IMP.py
      #python rubbeon_MTF_IMP_V2.py
      #python sar_break_V3.py
      #python index_power1h.py
      #python fx_avg_all_V2.py
      #python index_power.py

      - name: Commit and Push History
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add runner_history.json opportunity_stats.json trend_follower.json rubbeon_state.json rubbeon_MTF_IMP_state.json annual_v2_data.json annual_v2_state.json chg_cc_indices.json
          # Ne commiter que s'il y a des changements
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update runner and stats history [skip ci]" && git pull --rebase && git push)
